//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scraper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GunpostResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GunpostResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scraper.Resources.GunpostResources", typeof(GunpostResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.gunpost.ca.
        /// </summary>
        internal static string dmnGunPost {
            get {
                return ResourceManager.GetString("dmnGunPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alberta-74.
        /// </summary>
        internal static string rgnAlberta {
            get {
                return ResourceManager.GetString("rgnAlberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to british-columbia-158.
        /// </summary>
        internal static string rgnBritishColumbia {
            get {
                return ResourceManager.GetString("rgnBritishColumbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manitoba-209.
        /// </summary>
        internal static string rgnManitoba {
            get {
                return ResourceManager.GetString("rgnManitoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new-brunswick-216.
        /// </summary>
        internal static string rgnNewBrunswick {
            get {
                return ResourceManager.GetString("rgnNewBrunswick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newfoundland-223.
        /// </summary>
        internal static string rgnNewfoundland {
            get {
                return ResourceManager.GetString("rgnNewfoundland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nova-scotia-230.
        /// </summary>
        internal static string rgnNovaScotia {
            get {
                return ResourceManager.GetString("rgnNovaScotia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ontario-75.
        /// </summary>
        internal static string rgnOntario {
            get {
                return ResourceManager.GetString("rgnOntario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prince-edward-island-242.
        /// </summary>
        internal static string rgnPrinceEdwardIsland {
            get {
                return ResourceManager.GetString("rgnPrinceEdwardIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quebec-246.
        /// </summary>
        internal static string rgnQuebec {
            get {
                return ResourceManager.GetString("rgnQuebec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saskatchewan-280.
        /// </summary>
        internal static string rgnSaskatchewan {
            get {
                return ResourceManager.GetString("rgnSaskatchewan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to territories-290.
        /// </summary>
        internal static string rgnTerritories {
            get {
                return ResourceManager.GetString("rgnTerritories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DOMAIN]/[CATEGORY]/[TYPE]/[CITY]/[TITLE].
        /// </summary>
        internal static string urifGunPostAd {
            get {
                return ResourceManager.GetString("urifGunPostAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DOMAIN]/ads/[FILTERS].
        /// </summary>
        internal static string urifGunPostFilter {
            get {
                return ResourceManager.GetString("urifGunPostFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DOMAIN]/ads/l/[REGION].
        /// </summary>
        internal static string urifGunPostRegion {
            get {
                return ResourceManager.GetString("urifGunPostRegion", resourceCulture);
            }
        }
    }
}
