//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlScraper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UriLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UriLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HtmlScraper.Resources.UriLibrary", typeof(UriLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.firearmscanada.com.
        /// </summary>
        internal static string dmnFirearmsCanada {
            get {
                return ResourceManager.GetString("dmnFirearmsCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.gunpost.ca.
        /// </summary>
        internal static string dmnGunPost {
            get {
                return ResourceManager.GetString("dmnGunPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.guns.townpost.ca.
        /// </summary>
        internal static string dmnTownPostGuns {
            get {
                return ResourceManager.GetString("dmnTownPostGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DOMAIN]/firearms/[CATEGORY]/[REGION]/[TITLE].
        /// </summary>
        internal static string urifGPAd {
            get {
                return ResourceManager.GetString("urifGPAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /caliber/[CALIBRE].
        /// </summary>
        internal static string urifGPCal {
            get {
                return ResourceManager.GetString("urifGPCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /c/[CATEGORY].
        /// </summary>
        internal static string urifGPCat {
            get {
                return ResourceManager.GetString("urifGPCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /condition/[CONDITION].
        /// </summary>
        internal static string urifGPCond {
            get {
                return ResourceManager.GetString("urifGPCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /l/[REGION].
        /// </summary>
        internal static string urifGPLoc {
            get {
                return ResourceManager.GetString("urifGPLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manufacturer/[MANUF].
        /// </summary>
        internal static string urifGPMan {
            get {
                return ResourceManager.GetString("urifGPMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /model/[MODEL].
        /// </summary>
        internal static string urifGPMod {
            get {
                return ResourceManager.GetString("urifGPMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DOMAIN]/ads/[FILTERS].
        /// </summary>
        internal static string urifGPSearch {
            get {
                return ResourceManager.GetString("urifGPSearch", resourceCulture);
            }
        }
    }
}
